const data = {
    products: [
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
        {
            name: 'free shirt',
            category: 'Shirts',
            img: '/images/img1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReview: 10,
            countInStock: 20,
            description: 'a popular shirt',
        },
    ]
}